Import React in a allowSyntheticDefaultImports: false friendly way.
Otherwise you'll see the following error:

```
node_modules/@dnd-kit/core/dist/components/DndContext/DndContext.d.ts:1:8 - error TS1259: Module '"node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:62:1
    62 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag
```